### ISSUE TITLE
A question about something

### ISSUE THREAD

**Issue by guio75t855t** [CaffeineMC/sodium-fabric#1046]
I have a question. There is mod named better-rsqrt.
https://modrinth.com/mod/better-rsqrt
Does sodium has a feature like this?

**Comment by jellysquid3** [comment]
No. You should use the aforementioned mod if you want that functionality... though I'm not sure what the use case is. Maybe it's faster?

**Comment by Ilikemilkxd** [comment]
Ok thanks!
