### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [CaffeineMC/sodium-fabric#1198]
Port the mod Sodium to MC 1.12.2.

**Comment by FlashyReese** [comment]
https://github.com/CaffeineMC/caffeine-meta/wiki/FAQ#what-is-your-version-support-policy

**Comment by Kasia1403** [comment]
What ?! I don't understand this. Why Sodium can't be ported to MC 1.12.2 ?

**Comment by Kasia1403** [comment]
Do You maybe have changed Your mind ? But please say YES ! I'm begging so very much !

**Comment by jellysquid3** [comment]
No. I'm not porting the mod to such an old version of the game, it takes too much time and nobody else is volunteering to do it.

Please stop spamming our issue tracker, or you will be banned.
