### ISSUE TITLE
1.12.2 please. And I not joke !!!

### ISSUE THREAD

**Issue by Kasia1403** [CaffeineMC/sodium-fabric#1274]
As above.

**Comment by jellysquid3** [comment]
no

**Comment by Kasia1403** [comment]
My Minecraft lags and crashes !

**Comment by LambdAurora** [comment]
> My Minecraft lags and crashes ! I REALLY WANT this mod for MC 1.12.2.

Too bad for you but Minecraft modders are not obligated to bend to your will.

And Jellysquid already said no.

**Comment by jellysquid3** [comment]
We are not going to spend time back-porting to 5+ year old versions of the game. None of us have the time.
