### ISSUE TITLE
Game Freaking out

### ISSUE THREAD

**Issue by OrangeGlowest** [CaffeineMC/sodium-fabric#1711]
### Version information

mc1.19.4-0.4.11

### Expected Behavior

Nothing to freak out

### Actual Behavior

The Game Will freeze then if i click out and click back in the game will freak out

### Reproduction Steps

I just joined in my intel i3 10th gen processor

### Java version

Java 17

### CPU

Intel Core i3 10th gen

### GPU

This is laptop

**Comment by rilakuma123** [comment]
What does "freak out" mean? Is it crashing? Or is it something visual? If it's the latter, can you take a screen recording? On Windows you can use tools like ShareX, Snipping Tool, OBS, and Xbox Game Bar to do so. 
What operating system and version?
Are you playing in fullscreen? 
What other mods do you have, if any? 
Are you able to get in-game? Got a screenshot of F3?
What graphics driver version do you have?

**Comment by OrangeGlowest** [comment]
Visual

**Comment by OrangeGlowest** [comment]
I cant launch the game with sodium anymore but I am in windows 11 22H2, I am in playing in fullscreen. I could get in game but a visual bug with making the game screen freeze then it made me click out then back in and i could hear sounds from game but I could only see the loading screen  going black and loading screen really fast, i have to crash the game once this happens

**Comment by rilakuma123** [comment]
You did not provide all of the information I asked for so I can only guess, but it sounds like an issue with how Windows handles exclusive fullscreen and may not be a Sodium issue. Is this something you can reproduce without Sodium? Do you still see this issue when you add the [Borderless Mining](https://modrinth.com/mod/borderless-mining) mod, which is used to make Minecraft use borderless fullscreen?

**Comment by jellysquid3** [comment]
This is not a problem with Sodium, and we don't have enough information to resolve it. You probably just need to upgrade your graphics driver...
