### ISSUE TITLE
Render Distance resetting when exiting menu back to the default from before

### ISSUE THREAD

**Issue by OrangeGlowest** [CaffeineMC/sodium-fabric#1915]
### Bug Description

The Render distance resets when i am changing it. 

### Reproduction Steps

Open Minecraft, join anything, open render distance settings, set it to 3 (or any number), exit, go back in and it has reset

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12190074/latest.log)

### Crash Report

None Included

**Comment by OrangeGlowest** [comment]
One Thing to mention the only way to get it to permanently change is to use options.txt

**Comment by pajicadvance** [comment]
Please confirm if the issue happens with only Sodium installed.

**Comment by OrangeGlowest** [comment]
Hello, i figured out the mod "Bobby" was causing the issue
