### ISSUE TITLE
Sodium 1.17.1 | Memory Leak

### ISSUE THREAD

**Issue by DIDIRUS4** [CaffeineMC/sodium-fabric#747]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.494

### Expected Behavior

Check Additional information

### Actual Behavior

Check Additional information

### Reproduction Steps

Check Additional information

### Java version

AdoptOpenJDK 16

### CPU

I5 7600K 3.8 ghz 4/4 core/threads

### GPU

GTX 1060 6GB

### Additional information

Memory leak
It's going up if "new" chunks on client side loaded
RAM going up in task, but allocated memory in MC ~87% (Default after minecraft boot) (5GB RAM uses and highter if you play longer)
Without Sodium Memory going up, but allocated memore 100% and Minecraft uses in taskmng 4GB RAM
Ohhhh now I'm play with sodium and stay (without moves) - RAM is going up :(

With Sodium
![image](https://user-images.githubusercontent.com/77334306/125097565-f011ec00-e0de-11eb-9de0-e9ab565f6cdd.png)

Without Sodium
![image](https://user-images.githubusercontent.com/77334306/125097638-00c26200-e0df-11eb-839e-7d00d8bf5905.png)

**Comment by CamperSamu** [comment]
Fixed since Sodium 1.17.1-0.3.0 build 506 (https://github.com/CaffeineMC/sodium-fabric/commit/df1efdb3314c13f7724f3a74000e05f47f05c396)

**Comment by theTyrfing** [comment]
I am also experiencing the same issue when used with Iris Shaders. I am getting similar memory leak issues with the new implementation of Sodium with the fix provide in build 506. It seem like things still need to be matured.

**Comment by DynamicMC** [comment]
> ### Version information
> sodium-fabric-mc1.17.1-0.3.0+build.494
> 
> ### Expected Behavior
> Check Additional information
> 
> ### Actual Behavior
> Check Additional information
> 
> ### Reproduction Steps
> Check Additional information
> 
> ### Java version
> AdoptOpenJDK 16
> 
> ### CPU
> I5 7600K 3.8 ghz 4/4 core/threads
> 
> ### GPU
> GTX 1060 6GB
> 
> ### Additional information
> Memory leak
> It's going up if "new" chunks on client side loaded
> RAM going up in task, but allocated memory in MC ~87% (Default after minecraft boot) (5GB RAM uses and highter if you play longer)
> Without Sodium Memory going up, but allocated memore 100% and Minecraft uses in taskmng 4GB RAM
> Ohhhh now I'm play with sodium and stay (without moves) - RAM is going up :(
> 
> With Sodium
> ![image](https://user-images.githubusercontent.com/77334306/125097565-f011ec00-e0de-11eb-9de0-e9ab565f6cdd.png)
> 
> Without Sodium
> ![image](https://user-images.githubusercontent.com/77334306/125097638-00c26200-e0df-11eb-839e-7d00d8bf5905.png)

How did you got 1.17 version?

**Comment by DynamicMC** [comment]
How did you got 1.17 version?

**Comment by Kroppeb** [comment]
> I am also experiencing the same issue when used it with Iris Shaders. I am getting similar memory leak issues with the newer implementation of Sodium with the fix provide in build 506. Also, this crash is very regular and predictable basis. For me this point happens at the 45 minute mark with Iris Shader + Sodium and BSL Shaders. Would guys like the crash reports?

Iris has its own memory leak and the maintainers are actively looking into it. If you think you can provide useful information I'd suggest going to their discord and joining their efforts.

**Comment by DIDIRUS4** [comment]
But now Sodium stable, i think issue close.
If you have question or have information from Iris  (Leak Issue) pls feedback me DIDIRUS4#8994
Thx
