### ISSUE TITLE
So uh i got banned

### ISSUE THREAD

**Issue by Gavins38** [CaffeineMC/sodium-fabric#797]
idk where else to do this or how to appeal but i got banned in the discod because i posted a video that said Cringe then a electric gutarr plays and the mod said read the channel description and im thinking like the video description so i go there nothing is there i go back and say there is no description then im just banned : /

**Comment by Gavins38** [comment]
Im Dark_Oak_Block#3573 btw

**Comment by LucilleTea** [comment]
you were kicked, not banned.
i was referring to the discord channel description. this server is not a place for memes or trolling
